name: 'ArgoCD Application Updater'
author: '@betrybe'
description: 'Esta GitHub Action é utilizada para fazer atualizar secrets do Helm das aplicações em que o deploy é gerenciado pelo ArgoCD da Trybe.'
inputs:
  argocd_token:
    required: true
    description: 'ArgoCD token to do operations on server'
  environment:
    required: true
    description: 'Application environment'
  # previewAppRoute:
  #   required: false
  #   description: 'Regra de rota para usar em preview apps.'
  #   default: "$REPOSITORY-preview-app-$VERSION.betrybe.dev"

runs:
  using: 'composite'
  steps:
    - id: run
      shell: bash
      run: ${{ github.action_path }}/update_params.sh
  # image: 'Dockerfile'
      env:
        ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_token }}
        ARGOCD_SERVER: deploy.betrybe.com:443
        ARGOCD_VERSION: v2.6.2
        ENVIRONMENT: ${{ inputs.environment }}
