name: 'ArgoCD Application Updater'
author: '@betrybe'
description: 'Esta GitHub Action é utilizada para fazer atualizar secrets do Helm das aplicações em que o deploy é gerenciado pelo ArgoCD da Trybe.'
inputs:
  argocd_token:
    required: true
    description: 'ArgoCD token to do operations on server'
  env:
    required: true
    description: 'Application environment'
  secrets:
    required: false
    description: 'Secrets passed by param'
    default: ''
  # previewAppRoute:
  #   required: false
  #   description: 'Regra de rota para usar em preview apps.'
  #   default: "$REPOSITORY-preview-app-$VERSION.betrybe.dev"

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_token }}
    ENVIRONMENT: ${{ inputs.env }}
  args:
    - ${{ inputs.secrets }}
